name: tests

on:
  push:
    paths:
      - "concurrentbuffer/**"
      - "tests/**"
      - .github/workflows/tests.yml
  pull_request:
    paths:
      - "concurrentbuffer/**"
      - "tests/**"
      - .github/workflows/tests.yml

env:
  OS: ubuntu-latest
  PYTHON_VERSION: "3.8"


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install coveralls
          coverage run --source=concurrentbuffer -m pytest tests/

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.test_number }}
          parallel: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true