name: Tests

on:
  workflow_call:

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.8"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov===2.8.1
          pip install coveralls
          pytest tests tests --cov --cov-report term-missing

      - name: Upload coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
        shell: bash
        run: |
          pip install coveralls
          coveralls --service=github || echo "!! intermittent coveralls failure"

  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish || echo "!! intermittent coveralls failure"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}